### ISSUE TITLE
Suspended licences

### ISSUE THREAD

**Issue by pheeling** [pheeling/dinotronicCMDB#27]
What should happen with suspended licences? Sync for notice? deleted from freshservice inventory? sync but not counted in relationship build up.

**Comment by pheeling** [comment]
Solved with Pull Development Suspended licences #27. Solution set quantity to 0 if licence suspended. Max function updates according to higher count.

**Comment by AlexSchwerzmann** [comment]
Suspended onces can be deleted from Freshservice

**Comment by pheeling** [comment]
Assets welche suspended sind sollen nicht gesynct werden
Assets die existieren und suspended werden soll die Beziehung entfernt und gelöscht werden
